def initialize_hacks(playscene):
	log = playscene.log
	
	#log.set_int('HAS_SCOTTIE', 1)
	#log.set_int('HAS_BLUEPIN', 1)
	#log.set_int('HAS_RUBBERBAND', 1)
	#log.set_int('HAS_WRAPPEDGUM', 1)
	#log.set_int('SAW_NIGHTCLUB', 1)
	#log.set_int('TRAIN_ARRANGE_READY', 1)
	log.set_int('TRAIN_RUNNING', 1)
	log.set_int('TRAIN_FIXED', 1)
	#log.set_int('GATE_OPEN', 1)
	#log.set_int('HAS_VOLCANOPOG', 1)
	#log.set_int('HAS_LEGOPOG', 1)
	#log.set_int('HAS_TRAINPOG', 1)
	#log.set_int('HAS_HOUSE', 1)
	#log.set_int('HAS_WRAPPEDGUM', 2)
	log.set_int('HAS_WIZARD', 1)
	log.set_int('HAS_TRAINWHEEL', 2)
	log.set_int('HAS_GETOUTOFJAIL', 1)
	log.set_int('LEGO_STATE', 2)
	log.set_int('KNIGHTS_SHPIEL', 1)